- name: Create user and add them to a group
  hosts: webserver
  become: yes
  tasks:
    - name: Create a group
      ansible.builtin.group:
        name: ansible
        state: present

    - name: Create a User
      ansible.builtin.user:
        name: albus
        group: ansible
